version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
      - ./logs/sys_log:/var/log
    ports:
      - "8006:80"
    networks:
      - webnet
    restart: always
networks:
  webnet:
