version: "3"
services:
  web:
    image: tich.us:5000/spendee_app
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "8005:80"
    networks:
      - webnet
networks:
  webnet:
